# Generated by Django 6.0.2 on 2026-02-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_status_alter_userstatus_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatus',
            new_name='Status',
        ),
    ]
