# Generated by Django 6.0.2 on 2026-02-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_userstatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='status',
            name='slug',
        ),
    ]
